# Site settings
title: Nitin Choudhary's blog
email: 
description: "Blogs, tutorials and musings"
baseurl: ""
url: "http://nitinkgp23.github.io"
twitter_username: nitinkgp23
github_username:  nitinkgp23

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
